name: Deploy

on:
  workflow_dispatch:
    inputs:
      stack-id-fragment:
        required: true
        type: string
        description: 'Stack Identifier'
      code-version-ref:
        required: false
        type: string
        description: 'Optional: Git Commit Ref'

permissions:
  id-token: write      # Required for OIDC
  contents: read       # To clone the repo

jobs:
  display-inputs:
    runs-on: [ubuntu-latest]
    steps:
      - name: Display inputs
        run: |
          echo "inputs = ${{ toJson(inputs) }}"

  set-shared-vars:
    uses: ./.github/workflows/set-shared-vars.yml
    with:
      code-version-ref: ${{ inputs.code-version-ref }}
    secrets: inherit

  deploy:
    needs: [set-shared-vars]
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout working directory
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.code-version-ref }}

      - name: CDK synth
        uses: ./.github/actions/cdk-synth
        with:
          code-version-ref: ${{ needs.set-shared-vars.outputs.code-version-ref }}
          code-version-hash: ${{ needs.set-shared-vars.outputs.code-version-hash }}
          stack-id-fragment: ${{ inputs.stack-id-fragment }}
          gha-role-arn: ${{ needs.set-shared-vars.outputs.gha-role-arn }}

      - name: CDK deploy
        working-directory: ./infrastructure
        run: |
          npx cdk --app cdk.out --require-approval never deploy networking/networking-stack
