name: Deploy

on:
  workflow_dispatch:
    inputs:
      stack-id-fragment:
        required: true
        type: string
        description: 'Stack Identifier'
      code-version-ref:
        required: false
        type: string
        description: 'Optional: Git Commit Ref'

permissions:
  id-token: write      # Required for OIDC
  contents: read       # To clone the repo

jobs:
  display-inputs:
    runs-on: [ubuntu-latest]
    steps:
      - name: Display inputs
        run: |
          echo "inputs = ${{ toJson(inputs) }}"

  deploy:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - id: set-common-values
        name: Set Common Values
        run: |
          # Default the Git version reference and commit hash to those taken from the workflow run.
          code_version_ref=${{ github.ref_name }}
          code_version_hash=${{ github.sha }}

          # If the Git version reference is specified, use it and derive the Git commit hash from it.
          if [ ! -z "${{ inputs.code-version-ref }}" ]
          then
            code_version_ref=${{ inputs.code-version-ref }}
            code_version_hash=`git rev-parse ${{ inputs.code-version-ref }}`
          fi

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::815332568426:role/gha-interzonedev
          aws-region: us-west-1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./infrastructure
        run: npm install
