name: Deploy

on:
  workflow_dispatch:
    inputs:
      stack-id-fragment:
        required: true
        type: string
        description: 'Stack Identifier'

permissions:
  id-token: write      # Required for OIDC
  contents: read       # To clone the repo

jobs:
  display-inputs:
    runs-on: [ubuntu-latest]
    steps:
      - name: Display inputs
        run: |
          echo "inputs = ${{ toJson(inputs) }}"

  deploy:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::815332568426:role/gha-interzonedev
          aws-region: us-west-1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
